### ISSUE TITLE
It cannot be installed

### ISSUE THREAD

**Issue by cnutenor** [gsimon2/close-player-art#1]
It cannot be installed, it asks for another active module and even if it is activated it does not allow to install it and it continues asking for the activation of the show art module.
besides show art it indicates that another module must be installed but it does not indicate which one.

**Comment by gsimon2** [comment]
Curious. The only dependencies I have listed are the `Show Art` module and the Pathfinder 2e system, though that may not be a hard requirement, just was the extent of my testing when I first made this module. What system are you using?

**Comment by cnutenor** [comment]
oh! i use D&D5ed

**Comment by gsimon2** [comment]
Awesome. I have a test suite set up for 5e now, so should be able to verify fairly quickly. I will hopefully be able to get a bug fix out this week. Sorry for the inconvenience!

**Comment by gsimon2** [comment]
Just pushed out a bug fix for this (version 1.01): https://foundryvtt.com/packages/close-player-art/.

If you get time, try it out and let me know if this solved your issue. Thanks!

**Comment by cnutenor** [comment]
now work perfect!

Thanks!
