### ISSUE TITLE
don't work in v9

### ISSUE THREAD

**Issue by montver** [gsimon2/close-player-art#6]
Close player art doesn't work in foundry version v9

**Comment by gsimon2** [comment]
Confirmed. Adding this to my todo list. Thanks for bringing it to my attention!

**Comment by gsimon2** [comment]
Can you provide any more details? 

It seems to be working for me with both Pathfinder 2e and DnD5e systems.

Tested versions
Foundry: Version 9 - Build 245
DnD5e: 1.5.7
Pathfinder 2e: 3.2.2.10109

**Comment by montver** [comment]
sorry I realized that the error comes from using Monk's enhanced journal

**Comment by gsimon2** [comment]
Not a problem!
